------------------------
-------SEQUENCES--------
------------------------
CREATE SEQUENCE PUBLIC.USUARIO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE PUBLIC.CLIENTE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE PUBLIC.ENDERECO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE PUBLIC.UF_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

------------------------
--------TABELAS---------
------------------------

create table PUBLIC.USUARIO (
   IDUSUARIO            BIGINT               not null,
   LOGIN                VARCHAR(50)          not null,
   SENHA                VARCHAR(32)          not null,
   TIPOUSUARIO          CHAR(1)              not null
);

create table PUBLIC.CLIENTE (
   IDCLIENTE            BIGINT               not null,
   NOME                 VARCHAR(100)         null,
   CPF                  VARCHAR(11)          null,
   IDUSUARIO            BIGINT               not null
);

create table PUBLIC.ENDERECO (
   IDENDERECO           INT4                 null,
   CEP                  VARCHAR(8)           not null,
   LOGRADOURO           VARCHAR(100)         null,
   BAIRO                VARCHAR(100)         null,
   CIDADE               VARCHAR(100)         null,
   IDCLIENTE            BIGINT               not null,
   IDUF                 BIGINT               not null
);

create table PUBLIC.UF (
   IDUF                 BIGINT               not null,
   SIGLA                CHAR(2)              null,
   DESCRICAO            VARCHAR(100)         null
);

------------------------
-----CHAVES(PK/FK)------
------------------------

ALTER TABLE ONLY PUBLIC.USUARIO
    ADD CONSTRAINT USUARIO_PKEY PRIMARY KEY (IDUSUARIO);

ALTER TABLE ONLY PUBLIC.CLIENTE
    ADD CONSTRAINT CLIENTE_PKEY PRIMARY KEY (IDCLIENTE);

ALTER TABLE ONLY PUBLIC.ENDERECO
    ADD CONSTRAINT ENDERECO_PKEY PRIMARY KEY (IDENDERECO);

ALTER TABLE ONLY PUBLIC.UF
    ADD CONSTRAINT UF_PKEY PRIMARY KEY (IDUF);

ALTER TABLE ONLY PUBLIC.CLIENTE
    ADD CONSTRAINT USUARIO_IDUSUARIO_FK FOREIGN KEY (IDUSUARIO) REFERENCES PUBLIC.USUARIO(IDUSUARIO)
    on delete restrict on update restrict;

ALTER TABLE ONLY PUBLIC.ENDERECO
    ADD CONSTRAINT CLIENTE_IDCLIENTE_FK FOREIGN KEY (IDCLIENTE) REFERENCES PUBLIC.CLIENTE(IDCLIENTE)
    on delete restrict on update restrict;

ALTER TABLE ONLY PUBLIC.UF
    ADD CONSTRAINT UF_IDUF_FK FOREIGN KEY (IDUF) REFERENCES PUBLIC.UF(IDUF)
    on delete restrict on update restrict;

------------------------------
--INSERTS(CARGAS E DOMINIOS)--
------------------------------

INSERT INTO PUBLIC.USUARIO (IDUSUARIO,LOGIN,SENHA,TIPOUSUARIO) VALUES (1, 'admin','21232f297a57a5a743894a0e4a801fc3',1);
INSERT INTO PUBLIC.USUARIO (IDUSUARIO,LOGIN,SENHA,TIPOUSUARIO) VALUES (2, 'comum','e10adc3949ba59abbe56e057f20f883e',2);

INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (1, 'AC','Acre');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (2, 'AL','Alagoas');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (3, 'AP','Amapá');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (4, 'AM','Amazonas');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (5, 'BA','Bahia');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (6, 'CE','Ceará');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (7, 'DF','Distrito Federal');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (8, 'ES','Espírito Santo');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (9, 'GO','Goiás');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (10, 'MA','Maranhão');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (11, 'MT','Mato Grosso');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (12, 'MS','Mato Grosso do Sul');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (13, 'MG','Minas Gerais');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (14, 'PA','Pará');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (15, 'PB','Paraíba');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (16, 'PR','Paraná');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (17, 'PE','Pernambuco');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (18, 'PI','Piauí');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (19, 'RJ','Rio de Janeiro');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (20, 'RN','Rio Grande do Norte');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (21, 'RS','Rio Grande do Sul');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (22, 'RO','Rondônia');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (23, 'RR','Roraima');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (24, 'SC','Santa Catarina');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (25, 'SP','São Paulo');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (26, 'SE','Sergipe');
INSERT INTO PUBLIC.UF (IDUF,SIGLA,DESCRICAO) VALUES (27, 'TO','Tocantins');
